application: inukura01
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /json
  static_dir: json

- url: /.*
  script: helloworld.py
